name: Build and Syntax

on: 
push:
branches: ["main"]
pull_request:
branches: ["main"]

jobs:
build:
runs-on: ubunty-latest

steps: 
- name: Checkout code
uses: actions/checkout@v4

- name: Set up .NET SDK
uses: actions/setup-dotnet@v4
with: 
dotnet-version:'9.0'

- name: Restore dependencies
run: dotnet restore

- name: Run tests
run: dotnet test

- name: Build the project
run: dotnet build --configuration Release
